Integrate tests into autotools build system
Add automake files for the test binaries. If configured to do so,
install the test binaries to libexec/mtd-utils and use autoconf to
fix the paths in the test scripts.

Signed-off-by: David Oberhollenzer <david.oberhollenzer@sigma-star.at>
Signed-off-by: Richard Weinberger <richard@nod.at>

diff --git a/tests/ubi-tests/runubitests.sh.in b/tests/ubi-tests/runubitests.sh.in
--- a/tests/ubi-tests/runubitests.sh.in
+++ b/tests/ubi-tests/runubitests.sh.in
@@ -1,5 +1,11 @@
 #!/bin/sh -euf
 
+prefix=@prefix@
+exec_prefix=@exec_prefix@
+bindir=@bindir@
+libexecpath=@libexecdir@/mtd-utils
+TESTBINDIR=@testbindir@
+
 tests="mkvol_basic mkvol_bad mkvol_paral rsvol io_basic io_read io_update io_paral volrefcnt"
 
 fatal()
@@ -30,7 +36,7 @@ ubidev="$1"
 
 for t in $tests; do
 	echo "Running $t $ubidev"
-	"./$t" "$ubidev" || fatal "$t failed"
+	"$TESTBINDIR/$t" "$ubidev" || fatal "$t failed"
 done
 
 echo "SUCCESS"
